### ISSUE TITLE
Ruby 2.7.0 support warnings

### ISSUE THREAD

**Issue by swistaczek** [envygeeks/forwardable-extended#1]
```
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
ruby/2.7.0/gems/forwardable-extended-2.6.0/lib/forwardable/extended.rb:29: warning: The called method `rb_delegate' is defined here
```

**Comment by linnjason678** [comment]
What is your findings to support this Warning of Ruby 2.7.0?

**Comment by AvverbioPronome** [comment]
@envygeeks this breaks the 4.2.2 jekyll docker image.

**Comment by itsfaraaz** [comment]
get this error on ruby 3.1.2 when attempting to build jekyll:

```
/Users/faraazkh/.gem/ruby/3.1.2/gems/forwardable-extended-2.6.0/lib/forwardable/extended.rb:29:in `rb_delegate': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/liquid-tag-parser-1.9.0/lib/liquid/tag/parser.rb:34:in `<class:Parser>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/liquid-tag-parser-1.9.0/lib/liquid/tag/parser.rb:12:in `<class:Tag>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/liquid-tag-parser-1.9.0/lib/liquid/tag/parser.rb:11:in `<module:Liquid>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/liquid-tag-parser-1.9.0/lib/liquid/tag/parser.rb:10:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/tag.rb:7:in `require'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/tag.rb:7:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/context.rb:6:in `require_relative'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/context.rb:6:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/filters.rb:5:in `require_relative'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/filters.rb:5:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/env.rb:15:in `require_relative'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets/env.rb:15:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets.rb:21:in `require_relative'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll/assets.rb:21:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll-assets.rb:5:in `require_relative'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-assets-3.0.12/lib/jekyll-assets.rb:5:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/external.rb:58:in `require'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/external.rb:55:in `each'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/plugin_manager.rb:30:in `require_gems'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/plugin_manager.rb:22:in `conscientious_require'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/site.rb:114:in `setup'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/site.rb:32:in `initialize'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `new'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:30:in `process'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/bin/jekyll:25:in `load'
	from /Users/faraazkh/.gem/ruby/3.1.2/bin/jekyll:25:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/cli/exec.rb:28:in `run'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/cli.rb:463:in `exec'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/cli.rb:27:in `dispatch'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/cli.rb:18:in `start'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /Users/faraazkh/.gem/ruby/3.1.2/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
	from /Users/faraazkh/.gem/ruby/3.1.2/bin/bundle:25:in `load'
	from /Users/faraazkh/.gem/ruby/3.1.2/bin/bundle:25:in `<main>'
```
